assume all mds go in and output -> output always

diff --git a/.local/bin/md-to-slides b/.local/bin/md-to-slides
--- a/.local/bin/md-to-slides
+++ b/.local/bin/md-to-slides
@@ -1,14 +1,5 @@
 #!/bin/bash
-if [ -z "$1" ]; then
-    echo "requires one or more input files"
-    exit 1
-fi
-if [ -z "$2" ]; then
-    echo "requires an output file"
-    exit 1
-fi
-idx=1
-output="${@: -1}"
+output="output"
 echo "output: $output.pdf"
 tmpdir=$(mktemp -d)/
 defaultcss=slides.css
@@ -30,35 +21,34 @@ h1 {
 fi
 logfile=${tmpdir}log.txt
 _exit() {
-    echo "failed!"
-    cp $logfile log.txt
-    exit 1
-}
-touch $logfile
-for f in "$@"; do
-    if [[ "$f" == "$output" ]]; then
-        continue
-    fi
-    if echo $f | grep -q "\.md"; then
-        echo "converting: $f"
-        file=$tmpdir$idx.html
-        echo "<html><head><style>" > $file
-        cat $defaultcss >> $file
-        echo "</style></head><body>" >> $file
-        echo "<div id='slide-$idx'>" >> $file
-        epiphyte-markdown -file $f >> $file
-        if [ $? -ne 0 ]; then
-            _exit
-        fi
-        echo "</div></body></html>" >> $file
-        echo "$file" >> $logfile
-        cat $file >> $logfile
-    else
-        echo "$f is not a markdown file"
+    cp $logfile output.log
+    if [ -z "$1" ]; then
+        echo "failed!"
         exit 1
     fi
+}
+touch $logfile
+idx=1
+for f in $(ls *.md | sort); do
+    echo "converting: $f"
+    file=$tmpdir$idx.html
+    echo "<html><head><style>" > $file
+    cat $defaultcss >> $file
+    echo "</style></head><body>" >> $file
+    echo "<div id='slide-$idx'>" >> $file
+    epiphyte-markdown -file $f >> $file
+    if [ $? -ne 0 ]; then
+        _exit
+    fi
+    echo "</div></body></html>" >> $file
+    echo "$file" >> $logfile
+    cat $file >> $logfile
     idx=$((idx+1))
 done
+if [ $idx -eq 1 ]; then
+    echo "no markdown files found..."
+    _exit
+fi
 echo 'creating pdfs...'
 idx=1
 for f in $(find $tmpdir -type f -name "*.html"); do
@@ -77,5 +67,5 @@ pdfunite $pdfs $output.pdf
 if [ $? -ne 0 ]; then
     _exit
 fi
-cp $logfile output.log
+_exit "success"
 rm -rf $tmpdir
