track to a logfile

diff --git a/.local/bin/md-to-slides b/.local/bin/md-to-slides
--- a/.local/bin/md-to-slides
+++ b/.local/bin/md-to-slides
@@ -28,6 +28,13 @@ h1 {
     font-size: 48px;
 }" > $defaultcss
 fi
+logfile=${tmpdir}log.txt
+_exit() {
+    echo "failed!"
+    cp $logfile log.txt
+    exit 1
+}
+touch $logfile
 for f in "$@"; do
     if [[ "$f" == "$output" ]]; then
         continue
@@ -38,12 +45,14 @@ for f in "$@"; do
         echo "<html><head><style>" > $file
         cat $defaultcss >> $file
         echo "</style></head><body>" >> $file
+        echo "<div id='slide-$idx'>" >> $file
         epiphyte-markdown -file $f >> $file
         if [ $? -ne 0 ]; then
-            echo "failed!"
-            exit 1
+            _exit
         fi
-        echo "</body></html>" >> $file
+        echo "</div></body></html>" >> $file
+        echo "$file" >> $logfile
+        cat $file >> $logfile
     else
         echo "$f is not a markdown file"
         exit 1
@@ -54,11 +63,10 @@ echo 'creating pdfs...'
 idx=1
 for f in $(find $tmpdir -type f -name "*.html"); do
     file=$tmpdir$idx.pdf
-    echo "pdf'ing: $file"
-    cat $f | wkhtmltopdf -O landscape - $file > /dev/null
+    echo "making: $file"
+    cat $f | wkhtmltopdf -O landscape - $file >> $logfile 2>&1
     if [ $? -ne 0 ]; then
-        echo "failed!"
-        exit 1
+        _exit
     fi
     idx=$((idx+1))
 done
@@ -67,7 +75,7 @@ echo "merging pdfs..."
 pdfs=$(find $tmpdir -type f -name "*.pdf")
 pdfunite $pdfs $output.pdf
 if [ $? -ne 0 ]; then
-    echo "failed!"
-    exit 1
+    _exit
 fi
+cp $logfile output.log
 rm -rf $tmpdir
