better plugin handling

diff --git a/.local/bin/neovim-plugins b/.local/bin/neovim-plugins
--- a/.local/bin/neovim-plugins
+++ b/.local/bin/neovim-plugins
@@ -4,14 +4,20 @@ PLUGINS="$HOME/.config/nvim/pack/plugins/start"
 for PLUGIN in $(cat "$HOME/.config/voidedtech/neovim-plugins"); do
   BNAME=$(basename "$PLUGIN")
   CLONE="$PLUGINS/$BNAME"
-  echo "syncing: $BNAME"
-  if [ -d "$CLONE" ]; then
-    if ! git -C "$CLONE" pull origin "$(git -C "$CLONE" rev-parse --abbrev-ref HEAD)"; then
-      echo "  -> failed to update"
-    fi
-  else
-    if ! git clone "$PLUGIN" "$CLONE" --single-branch; then
-      echo "  -> failed to clone"
-    fi
-  fi
+  (
+    {
+      echo "sync"
+      if [ -d "$CLONE" ]; then
+        if ! git -C "$CLONE" pull --quiet origin "$(git -C "$CLONE" rev-parse --abbrev-ref HEAD)"; then
+          echo "  -> failed to update"
+        fi
+      else
+        if ! git clone --quiet "$PLUGIN" "$CLONE" --single-branch; then
+          echo "  -> failed to clone"
+        fi
+      fi
+      echo "done"
+    } 2>&1 | sed "s#^#$BNAME: #g"
+  ) &
 done
+wait
