share a config a bit

diff --git a/.local/bin/sys-update b/.local/bin/sys-update
--- a/.local/bin/sys-update
+++ b/.local/bin/sys-update
@@ -71,9 +71,12 @@ _apps() {
 _sync() {
   local d parent
   parent=/mnt/workdir/host
-  for d in $(ls "$parent"); do
+  if ! cp "$parent/data/ssh.config" "$HOME/.ssh/config"; then
+    echo "missing host ssh config"
+  fi
+  for d in $(ls "$parent" | grep -v data); do
     echo "syncing: $d"
-    if ! rsync -avcn --delete-after "$parent/$d/" "store:/mnt/store/active/$d/"; then
+    if ! rsync -avc --delete-after "$parent/$d/" "store:/mnt/store/active/$d/"; then
       echo "unable to sync: $d"
     fi
   done
