migrated to compiled

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,7 +24,26 @@ _lsfiles() {
   done
 }
 
+_builds() {
+  local d
+  for d in src/*; do
+    mkdir -p "$d/bin"
+    if ! (cd $d && deno task compile); then
+      echo "build failed: $d"
+      return
+    fi
+  done
+}
+
+_installs() {
+  local f
+  for f in $(find src/ -type f -wholename "*/bin/*"); do
+    echo "install -Dm755 $f $HOME/.local/bin/$(basename $f)"
+  done
+}
+
 _makefile() {
+  _builds
   echo "all:"
   {
     {
@@ -36,6 +55,7 @@ _makefile() {
         fi
       fi
     } | awk '!x[$0]++'
+    _installs
     echo "rm Makefile"
   } | sed 's/^/\t/g'
 }
