this builds/works

diff --git a/lib/containers/website/configure b/lib/containers/website/configure
--- a/lib/containers/website/configure
+++ b/lib/containers/website/configure
@@ -1,9 +1,15 @@
 #!/usr/bin/env bash
 BIN=bin/
 CLONE=$BIN/voidedtech.com
+RSRC=$BIN/resources
+if [ -z "$WEBSITE_RESOURCES" ]; then
+    echo "website resources not found"
+    exit 1
+fi
 rm -rf $BIN/
 mkdir -p $BIN
 git clone https://github.com/enckse/voidedtech.com $CLONE
+rsync -avc $WEBSITE_RESOURCES $RSRC
 
 podman build -f Containerfile -t website
 git -C $CLONE status
