handle user updates via neovim command

diff --git a/linux/.config/nvim/user-updates b/linux/.config/nvim/user-updates
--- a/linux/.config/nvim/user-updates
+++ b/linux/.config/nvim/user-updates
@@ -7,17 +7,39 @@ PLUGINS=(
   "https://github.com/echasnovski/mini.nvim"
 )
 
+if [ -z "$1" ]; then
+  echo "command required"
+  exit 1
+fi
+CMD="$1"
+case "$CMD" in
+  "init")
+    ;;
+  "update")
+    ;;
+  *)
+    echo "unknown command: $CMD"
+    exit 1
+    ;;
+esac
+
 _plugins() {
   local bname url dest
-  echo "updating plugins..."
+  if [ "$CMD" == "update" ]; then
+    echo "updating plugins..."
+  fi
   for url in "${PLUGINS[@]}"; do
     bname=$(basename "$url")
-    echo "updating: $bname"
+    echo "$CMD: $bname"
     dest="$PACK/$bname"
     if [ ! -d "$dest" ]; then
       if ! git clone "$url" "$dest" --single-branch; then
         echo "unable to clone"
         exit 1
+      fi
+    else
+      if [ "$CMD" == "init" ]; then
+        continue
       fi
     fi
     if ! git -C "$dest" pull origin "$(git -C "$dest" rev-parse --abbrev-ref HEAD)"; then
@@ -29,4 +51,3 @@ _plugins() {
 }
 
 _plugins
-abw sync
