rebuild all is a better option for now

diff --git a/host/configure b/host/configure
--- a/host/configure
+++ b/host/configure
@@ -8,16 +8,22 @@ if [ "$UID" -eq 0 ]; then
   echo 'do NOT run as root'
   exit 1
 fi
+REBUILD=0
 if [ -n "$1" ]; then
-  FILE="$1.Containerfile"
-  if [ ! -s "$FILE" ]; then
-    echo "no containerfile definition found"
+  if [ "$1" == "build" ]; then
+    REBUILD=1
+  else
+    echo "unknown command: $1"
     exit 1
   fi
-  if ! podman build -f "$FILE" -t "$1"; then
-    echo "podman failed"
-    exit 1
-  fi
+fi
+if [ "$REBUILD" -eq 1 ]; then
+  for t in $(ls *.Containerfile | cut -d "." -f 1); do
+    if ! podman build -f "$t.Containerfile" -t "$t"; then
+      echo "podman failed"
+      exit 1
+    fi
+  done
 fi
 EXPORTS="$HOME/.hostrc"
 echo "#!/usr/bin/env bash" > "$EXPORTS"
