deprecate abw

diff --git a/containers/configure b/containers/configure
--- a/containers/configure
+++ b/containers/configure
@@ -28,11 +28,13 @@ workbench-$t() {
     exit 1
   fi
   h=$CONTAINER_HOME/$t
-  if ! distrobox-create --name $t --image localhost/$t --home \$h --volume $HOME/workspace:\$h/workspace --volume $HOME/downloads:\$h/downloads; then
-    echo "failed to create $t"
-    exit 1
+  if distrobox-list | cut -d "|" -f 2 | grep -q -v '$t'; then
+    if ! distrobox-create --name $t --image localhost/$t --home \$h --volume $HOME/workspace:\$h/workspace --volume $HOME/downloads:\$h/downloads; then
+      echo "failed to create $t"
+      exit 1
+    fi
   fi
-  exec distrobox-enter --name $t --no-workdir
+  distrobox-enter --name $t --no-workdir
 }
 EOF
   done
