restore rpm builds

diff --git a/.bin/host/enter-toolbox b/.bin/host/enter-toolbox
--- a/.bin/host/enter-toolbox
+++ b/.bin/host/enter-toolbox
@@ -16,6 +16,10 @@ _update() {
     echo "$1 does not exist"
     return
   fi
+  if ! toolbox run --container "$1" sudo cp "$HOME/.config/voidedtech/voidedtech.repo" /etc/yum.repos.d/voidedtech.repo; then
+    echo "failed to setup local repo"
+    exit 1
+  fi
   if ! toolbox run --container "$1" sudo dnf update; then
     echo "failed to dnf update"
     exit 1
