replace tabs

diff --git a/.bin/git-oclone b/.bin/git-oclone
--- a/.bin/git-oclone
+++ b/.bin/git-oclone
@@ -3,51 +3,51 @@ CONFIG="$HOME/.config/voidedtech/oclone.yml"
 HIST="$HOME/.cache/oclone.hst"
 
 oclone() {
-	local in spec dst url clone cfg
-	in="$1"
-	if [ "$in" == "--list" ]; then
+  local in spec dst url clone cfg
+  in="$1"
+  if [ "$in" == "--list" ]; then
     {
-			yq ".specs[].name" "$CONFIG" | sed 's#$#/#g'
-			if [ -e "$HIST" ]; then
-				cat "$HIST"
-			fi
-		} | sort
-		return
-	fi
-	repo=$(echo "$in" | cut -d '/' -f 1)
-	spec=$(yq ".specs[] | select (.name == \"$repo\")" "$CONFIG")
-	if [ -z "$spec" ]; then
-		echo "invalid argument, spec not found"
-		exit 1
-	fi
-	url=$(echo "$spec" | yq '.url')
-	clone="$url$(echo "$in" | cut -d "/" -f 2-)"
-	if ! git clone "$clone" "${@:2}"; then
-		echo "clone failed"
-		exit 1
-	fi
-	touch "$HIST"
-	awk -v line="$in" 'FNR==NR && line==$0{f=1; exit} 
+      yq ".specs[].name" "$CONFIG" | sed 's#$#/#g'
+      if [ -e "$HIST" ]; then
+        cat "$HIST"
+      fi
+    } | sort
+    return
+  fi
+  repo=$(echo "$in" | cut -d '/' -f 1)
+  spec=$(yq ".specs[] | select (.name == \"$repo\")" "$CONFIG")
+  if [ -z "$spec" ]; then
+    echo "invalid argument, spec not found"
+    exit 1
+  fi
+  url=$(echo "$spec" | yq '.url')
+  clone="$url$(echo "$in" | cut -d "/" -f 2-)"
+  if ! git clone "$clone" "${@:2}"; then
+    echo "clone failed"
+    exit 1
+  fi
+  touch "$HIST"
+  awk -v line="$in" 'FNR==NR && line==$0{f=1; exit} 
                               END{if (!f) print line >> FILENAME}' "$HIST"
-	cfg=$(echo "$spec" | yq '.config')
-	if [ -z "$cfg" ]; then
-		return
-	fi
-	dst=$(echo "$in" | rev | cut -d '/' -f 1 | rev)/.git/config
-	if [ ! -e "$dst" ]; then
-		echo "unable to set config"
-		exit 1
-	fi
-	echo "$cfg" >> "$dst"
+  cfg=$(echo "$spec" | yq '.config')
+  if [ -z "$cfg" ]; then
+    return
+  fi
+  dst=$(echo "$in" | rev | cut -d '/' -f 1 | rev)/.git/config
+  if [ ! -e "$dst" ]; then
+    echo "unable to set config"
+    exit 1
+  fi
+  echo "$cfg" >> "$dst"
 }
 
 if [ -z "$1" ]; then
-	echo "argument required"
-	exit 1
+  echo "argument required"
+  exit 1
 fi
 if [ ! -e "$CONFIG" ]; then
-	echo "$CONFIG is missing"
-	exit 1
+  echo "$CONFIG is missing"
+  exit 1
 fi
 
 oclone "$@"
