allow updates

diff --git a/.bin/git-mirror b/.bin/git-mirror
--- a/.bin/git-mirror
+++ b/.bin/git-mirror
@@ -1,10 +1,5 @@
 #!/usr/bin/env bash
 CONFIG="$HOME/.config/voidedtech/git.yml"
-REPO="$1"
-if [ -z "$REPO" ]; then
-	echo "repository not given"
-	exit 1
-fi
 REMOTE=$(yq ".specs[] | select (.name == \"upstream\")" $CONFIG)
 if [ -z "$REMOTE" ]; then
 	echo "no remotes set for upstream?"
@@ -18,6 +13,17 @@ fi
 if [ ! -d "$STORE" ]; then
 	echo "$STORE does not exist"
 	exit 1
+fi
+REPO="$1"
+if [ -z "$REPO" ]; then
+	echo "fetching mirror updates"
+	for r in $(ls $STORE); do
+		echo "-> $r"
+		if ! git -C "$STORE/$r" fetch; then
+			echo "failed"
+		fi
+	done
+	exit 0
 fi
 DIR=$STORE/$(echo "$REPO" | rev | cut -d '/' -f 1 | rev)
 if [ -d "$DIR" ]; then
