Adding SOCKS proxying helper

diff --git a/.bin/helper_cache b/.bin/helper_cache
--- a/.bin/helper_cache
+++ b/.bin/helper_cache
@@ -17,6 +17,7 @@ INSTALL_CHROME_KEY="setup-chrome"
 PROXY_CHROME_KEY="chrome-proxy"
 TEXT_EDITOR_KEY="text-editor"
 DMENU_KEY="dmenu-wrapper"
+SOCKS_KEY="socks"
 GOOGLE_CHROME_PRIVATE_KEY="$GOOGLE_CHROME_KEY$PRIVATE_KEY"
 PASS_FILE=${SYNCED_PATH}passwords
 CACHE_PATH=$HOME/.cache/helper_cache/
@@ -27,6 +28,29 @@ VIMRC_TXT=$HOME/.vimrc_text
 VIMRC_TMP=$USER_TMP/.vimrc_txt
 DMENU_LIST="$SEARCH_KEY $SEARCH_PRIVATE_KEY $PASSWORD_KEY $VOLUME_KEY $CHROME_KEY $CHROME_PRIVATE_KEY $GOOGLE_CHROME_KEY $GOOGLE_CHROME_PRIVATE_KEY $PROXY_CHROME_KEY"
 DMENU_INCLUDE="$HOME/.config/menus/dmenu_entries"
+START_PORT=$((PROXY_PORT+1))
+END_PORT=$((START_PORT+1000))
+
+function socks()
+{
+    if [ -z "$1" ]; then
+        echo "host required"
+        exit -1
+    fi
+    host=$1
+    port=$2
+    if [ -z "$port" ]; then
+        port=$(shuf -i ${START_PORT}-${END_PORT} -n 1)
+    fi
+    echo "connecting to $host via $port"
+    cmd=$(socks-command "$port" "$host")
+    if [ $? -ne 0 ]; then
+        echo "unable to open connection..."
+        echo $cmd
+        exit -1
+    fi
+    $cmd
+}
 
 function text-editor()
 {
@@ -56,7 +80,11 @@ function dmenu-wrapper()
 
 function proxy-chrome()
 {
-    chromium --proxy-server="socks5://localhost:$PROXY_PORT" --host-resolver-rules="MAP * 0.0.0.0 , EXCLUDE localhost"
+    use_port=$PROXY_PORT
+    if [ ! -z "$1" ]; then
+        use_port=$1
+    fi
+    chromium --proxy-server="socks5://localhost:$use_port" --host-resolver-rules="MAP * 0.0.0.0 , EXCLUDE localhost"
 }
 
 function markdown()
@@ -151,6 +179,7 @@ function get-help()
     $PROXY_CHROME_KEY (chrome with SOCKS proxy)
     $TEXT_EDITOR_KEY (text editor/documentation editor)
     $DMENU_KEY (dmenu wrapper)
+    $SOCKS_KEY (socks proxying)
 "
 }
 
@@ -213,6 +242,9 @@ function install-chrome()
 if [ ! -z $1 ]; then
     NEED_HELP=0
     case $1 in
+        $SOCKS_KEY)
+            socks ${@:2}
+            ;;
         $PASSWORD_KEY)
             passwords
             ;;
@@ -258,7 +290,7 @@ if [ ! -z $1 ]; then
             csv-processing $2
             ;;
         $PROXY_CHROME_KEY)
-            proxy-chrome
+            proxy-chrome $2
             ;;
         $TEXT_EDITOR_KEY)
             text-editor ${@:2}
