make sure home exists and the input machine was given

diff --git a/.bin/machinectl-helper b/.bin/machinectl-helper
--- a/.bin/machinectl-helper
+++ b/.bin/machinectl-helper
@@ -61,6 +61,10 @@ function create()
 
 function is-running()
 {
+    if [ -z "$1" ]; then
+        echo "argument required..."
+        exit 1
+    fi
     machinectl status $1 &> /dev/null
     if [ $? -eq 0 ]; then
         echo "$1 is running..."
@@ -92,7 +96,9 @@ function refresh()
         to=$(echo $f | cut -d ":" -f 2)
         rsync -vrc $from $CONT_PATH$to
     done
-    chown -R $USER_NAME:$USER_NAME ${CONT_PATH}/home/enck
+    full_home=${CONT_PATH}/$USER_HOME
+    mkdir -p $full_home
+    chown -R $USER_NAME:$USER_NAME $full_home
 }
 
 function pack()
