merging more scripts

diff --git a/.bin/status b/.bin/status
--- a/.bin/status
+++ b/.bin/status
@@ -3,6 +3,8 @@ source $HOME/.bin/common
 STAT_GIT=${USER_TMP}/.stats.git
 GIT_PARTIAL_PATTERN="weechat|random_seed"
 STAT_LOCK=${USER_TMP}/.statlock
+CONF_HOME=${HOME_CONF}home
+PACKAGE_SET=${CONF_HOME}/packages
 
 _get-git-folders() {
     local res f d
@@ -85,6 +87,49 @@ stats() {
     rm -f $STAT_LOCK
 }
 
+_booting() {
+    echo "booting up..."
+    # cleanup file
+    rm -f $HOME/.python_history*
+    rm -f $HOME/.wget-hsts*
+    rm -f $HOME/.esd_auth*
+    rm -f $HOME/.lesshst*
+    rm -f $PROFILE_TMP*
+    rm -f $SYS_ONLINE
+    
+    # packages
+    /usr/bin/pacman -Qqe > $PACKAGE_SET
+
+    # mail validation
+    find $MAIL_DIR -type f -exec file {} \; | grep -v "\.notmuch\/" | grep -v -E "(ASCII|UTF-8 Unicode|ISO-8859) text(,|$)" | systemd-cat -t "mailsync" -p err
+
+    wsw reload
+}
+
+_daily() {
+    local f xsess
+    f=$USER_TMP/maintain.$(date +%Y-%m-%d)
+    if [ ! -e $f ]; then
+        echo "running daily checks..."
+        xsess=$HOME/.xsession-errors
+        if [ -e $xsess ]; then
+            cat $xsess >> $USER_TMP/xsession.$(date +%Y-%m-%d)
+            rm -f $xsess
+        fi
+        echo "clearing user tmp..."
+        mkdir -p $USER_TMP
+        find $USER_TMP* -mtime 1 -type f -exec rm {} \;
+        find $USER_TMP -empty -type d -delete
+        find $HOME/.vim/{swap,undo} -mmin +1440 -type f -exec rm {} \;
+        echo "validate syncing"
+        journalctl -t sync --since "7 days ago" | grep -q "local sync completed"
+        if [ $? -ne 0 ]; then
+            echo "no recent successful syncs" | systemd-cat -p err -t "maintain"
+        fi
+    fi
+}
+
+
 if [ -z "$1" ]; then
     stats &
 else
@@ -105,6 +150,12 @@ else
             ;;
         "email")
             _unread
+            ;;
+        "daily")
+            _daily
+            ;;
+        "boot")
+            _booting
             ;;
         *)
             echo "unknown command: $1"
