config file

diff --git a/.bin/upstreams b/.bin/upstreams
--- a/.bin/upstreams
+++ b/.bin/upstreams
@@ -1,28 +1,27 @@
 #!/bin/bash
 UPSTREAM="$HOME/.cache/upstreams/"
+CONF="$HOME/.config/voidedtech/upstream.yml"
 mkdir -p "$UPSTREAM"
 PKGS="$1"
 
-_ls() {
-  echo "stagit:git://git.codemadness.org/stagit"
-  echo "gopls:https://github.com/golang/tools"
-  echo "helix:https://github.com/helix-editor/helix"
-  echo "filebrowser:https://github.com/filebrowser/filebrowser"
-  echo "mblaze:https://github.com/leahneukirchen/mblaze"
-  echo "yq:https://github.com/mikefarah/yq"
-  echo "isync:https://git.code.sf.net/p/isync/isync"
-  echo "revive:https://github.com/mgechev/revive"
-  echo "staticcheck:https://github.com/dominikh/go-tools"
-}
-
 _externals() {
-  local r n curr prev changed
+  local r n curr prev changed cnt len
+  if [ ! -e "$CONF" ]; then
+    echo "no $CONFIG file"
+    exit 1
+  fi
   changed=0
-  for r in $(_ls); do
-    n=$(echo "$r" | cut -d ":" -f 1)
+  cnt=0
+  len=$(yq '.sources | length' "$CONF")
+  if [ -z "$len" ] || [ "$len" -le 0 ]; then
+    echo "invalid sources"
+    exit 1
+  fi
+  while [ "$cnt" -lt "$len" ]; do
+    n=$(yq ".sources[$cnt].name" "$CONF")
+    r=$(yq ".sources[$cnt].url" "$CONF")
     curr="${UPSTREAM}$n"
     prev="$curr.prev"
-    r=$(echo "$r" | cut -d ":" -f 2-)
     echo "checking: $r ($n)"
     if ! git ls-remote --tags "$r" > "$curr"; then
       echo "failed to fetch: $r"
@@ -38,6 +37,7 @@ _externals() {
     else
       mv "$curr" "$prev"
     fi
+    cnt=$((cnt+1))
   done
   exit $changed
 }
