do some verifying before handling further steps

diff --git a/bin/linux/apod b/bin/linux/apod
--- a/bin/linux/apod
+++ b/bin/linux/apod
@@ -38,6 +38,7 @@ _clean() {
         done
     done
     echo "cleanup complete"
+    _duplicates
 }
 _get_packages() {
     local f bname name
@@ -98,6 +99,7 @@ _duplicates() {
     fi
 }
 
+
 errors=""
 mkdir -p $CACHE $CONFS
 _clean
@@ -115,17 +117,13 @@ _podmanrun() {
         --workdir /apk \
         $NAME $@
     if [ $? -ne 0 ]; then
-        errors="$errors$@ "
+        _clean
+        echo "^ error encountered"
+        exit 1
     fi
 }
 _podmanrun doas /sbin/apk update
+_podmanrun abuild sanitycheck
+_podmanrun abuild verify
 _podmanrun abuild -r
 _clean
-_duplicates
-if [ -n "$errors" ]; then
-    echo
-    echo "ERROR:"
-    echo "  -> $errors"
-    echo
-    exit 1
-fi
