changing sync behavior

diff --git a/.local/bin/darwin/system-sync b/.local/bin/darwin/system-sync
--- a/.local/bin/darwin/system-sync
+++ b/.local/bin/darwin/system-sync
@@ -1,5 +1,6 @@
 #!/bin/sh
-DIR="$HOME/.local/voidedtech/synced"
+ACTIVE="$HOME/Active"
+DIR="$ACTIVE/air"
 
 rm -f "$DIR/Brewfile"
 if ! (cd "$DIR" && brew bundle dump); then
@@ -12,7 +13,9 @@ if ! cp "$HOME/.config/vm/alpine.json" "$DIR/vm.json"; then
   exit 1
 fi
 
-if ! rsync -avc --delete-after "$DIR/" "mini.voidedtech.com:~/Active/air/"; then
-  echo "failed to rsync state"
-  exit 1
-fi
+for SUB in $(ls "$ACTIVE"); do
+  if ! rsync -avc --delete-after "$ACTIVE/$SUB/" "mini.voidedtech.com:~/Active/$SUB/"; then
+    echo "failed to rsync state"
+    exit 1
+  fi
+done
