version 2.0 firmware

diff --git a/containers/kinesis/configure b/containers/kinesis/configure
--- a/containers/kinesis/configure
+++ b/containers/kinesis/configure
@@ -4,9 +4,12 @@ CACHE=$HOME/.cache/adv360
 mkdir -p $BIN
 if [ ! -d $CACHE ]; then
     git clone https://github.com/KinesisCorporation/Adv360-Pro-ZMK $CACHE
-    git -C $CACHE checkout V1.0
+    git -C $CACHE checkout V2.0
 fi
 rsync -avc --delete-after $CACHE $BIN
 PATCH=$PWD/keys.patch
-(cd $BIN/adv360 && patch -p1 < $PATCH)
+if ! (cd $BIN/adv360 && patch -p1 < $PATCH); then
+    echo "patch failed"
+    exit 1
+fi
 podman build --volume $BIN:/out/ -f Containerfile -t kinesis
